buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

// Menjaga agar seluruh task kompilasi di semua sub-project menggunakan UTF-8
allprojects {
    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}
